name       : python-absl-py
version    : 0.8.0
release    : 3
source     :
    - https://github.com/abseil/abseil-py/archive/pypi-v0.8.0.tar.gz : 280c76ec0c9ab7a1dff550cdc37b7c7cd28551103dc3955202760ea8e381aa9d
license    : Apache-2.0
component  : programming.python
summary    : Abseil Python Common Libraries
description: |
    A collection of Python library code from Google's Python code base for building Python applications.
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
