name       : python-absl-py
version    : 0.8.1
release    : 5
source     :
    - https://github.com/abseil/abseil-py/archive/pypi-v0.8.1.tar.gz : 0a145cb81101d1add8b87eaae58c5d51521084bf7cc4e4654928b326a864c6c3
license    : Apache-2.0
component  : programming.python
summary    : Abseil Python Common Libraries
description: |
    A collection of Python library code from Google's Python code base for building Python applications.
rundeps    :
    - python-six
build      : |
    %python3_setup
install    : |
    %python3_install
